title: "Diffraction Stuff"
description: Diffraction and diffraction gratings in graphics.
show_downloads: false
baseurl: "/cs354-final-report"
url: "http://tabenmalik.github.io"
theme: jekyll-theme-tactile